name: trodi
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - h5py
  # - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
    #  - optuna
